const fieldFlowCompanies = [
  { customer_id: "cust_00001", business_name: "Bright Spark Electric" },
  { customer_id: "cust_00002", business_name: "Reliable Rooter Plumbing" },
  { customer_id: "cust_00003", business_name: "Spotless Sweep Cleaning Co." },
  { customer_id: "cust_00004", business_name: "Solo Circuit Electrical" },
  { customer_id: "cust_00005", business_name: "Northside Plumbing & Drain" },
  { customer_id: "cust_00006", business_name: "Fresh Start Home Cleaning" },
  { customer_id: "cust_00007", business_name: "Cool Breeze HVAC" },
  { customer_id: "cust_00008", business_name: "Green Thumb Landscaping" },
  { customer_id: "cust_00009", business_name: "Handy Hank's Repairs" },
  { customer_id: "cust_00010", business_name: "TrueLine Painting" },
  { customer_id: "cust_00011", business_name: "Metro Electric Solutions" },
  { customer_id: "cust_00012", business_name: "Pipeline Pros Plumbing" },
  { customer_id: "cust_00013", business_name: "Sparkle & Shine Cleaners" },
  { customer_id: "cust_00014", business_name: "All Seasons HVAC" },
  { customer_id: "cust_00015", business_name: "Regional Comfort Systems" },
  { customer_id: "cust_00016", business_name: "Curb Appeal Landscaping Group" },
  { customer_id: "cust_00017", business_name: "One Call Handyman Services" },
  { customer_id: "cust_00018", business_name: "Precision Painters LLC" },
  { customer_id: "cust_00019", business_name: "Downtown Drain Doctors" },
  { customer_id: "cust_00020", business_name: "Citywide Cleaning Solutions" },
  { customer_id: "cust_00021", business_name: "Ironclad Electric" },
{ customer_id: "cust_00022", business_name: "Neighborhood Plumbing Co." },
{ customer_id: "cust_00023", business_name: "Cascade Home Services" },
{ customer_id: "cust_00024", business_name: "Meridian Home Solutions" },
{ customer_id: "cust_00025", business_name: "Vantage Group Home Services" }
];